###
# Configuration for Vagrant
###
name: linuxtuki
production:
  # This is used to automatically fetch data from a staging/production environment
  domain: linux-tuki.fi.seravo.com
  ssh_port: 10367
  url: https://linux-tuki.fi.seravo.com
development:
  # Domains are automatically mapped to Vagrant with /etc/hosts modifications
  domains:
    - linuxtuki.local
  # If you want to use zeroconf (.local domains) in your network you can use this.
  #avahi: true